version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - docker.env
    networks:
      - freecodecamp

  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    env_file:
      - docker.env
    networks:
      - freecodecamp

networks:
  freecodecamp:
